/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.sistemavendas.Presentation;

import br.edu.ifnmg.tads.sistemavendas.DataAcess.PessoaDAO;
import br.edu.ifnmg.tads.sistemavendas.DomainModel.Pessoa;
import java.sql.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class frmPessoaCadastrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPessoaCadastrar
     */
    public frmPessoaCadastrar() {
        initComponents();
    }
    PessoaDAO pessoaDao = new PessoaDAO();
    Pessoa pessoa = new Pessoa();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvarCadastroPessoa = new javax.swing.JToggleButton();
        btnApagar = new javax.swing.JButton();
        lblNomePessoaCadastro = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDataNascimentoCadastroPessoa = new javax.swing.JLabel();
        txtfDataNascimentoCadastroPessoa = new javax.swing.JFormattedTextField();

        btnSalvarCadastroPessoa.setText("Salvar");
        btnSalvarCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroPessoaActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        lblNomePessoaCadastro.setText("Nome:");

        lblDataNascimentoCadastroPessoa.setText("Data Nascimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomePessoaCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataNascimentoCadastroPessoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfDataNascimentoCadastroPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvarCadastroPessoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagar)))
                        .addGap(0, 181, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePessoaCadastro)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimentoCadastroPessoa)
                    .addComponent(txtfDataNascimentoCadastroPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastroPessoa)
                    .addComponent(btnApagar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroPessoaActionPerformed

        try {

            Calendar Data = GregorianCalendar.getInstance();
            pessoa.setNome(txtNome.getText());
            pessoa.setDataNascimento(Date.valueOf(txtfDataNascimentoCadastroPessoa.getText()));
        } catch (Exception ex) {
            Logger.getLogger(frmPessoaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(JOptionPane.showConfirmDialog(rootPane,"Deseja salvar?") == 0){
            pessoaDao.Salvar(pessoa);
            JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane,"Operação Cancelada!");
        }
    }//GEN-LAST:event_btnSalvarCadastroPessoaActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed

        try{
            if(JOptionPane.showConfirmDialog(rootPane,"Deseja Apagar?") == 0){
                pessoaDao.Remover(pessoa);
                JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso!");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Operação Cancelada!");
            }
        }catch (Exception ex) {
            Logger.getLogger(frmPessoaCadastrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JToggleButton btnSalvarCadastroPessoa;
    private javax.swing.JLabel lblDataNascimentoCadastroPessoa;
    private javax.swing.JLabel lblNomePessoaCadastro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtfDataNascimentoCadastroPessoa;
    // End of variables declaration//GEN-END:variables
}
