/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.sistemavendas.Presentation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Diego
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuSairSistema = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        mnuPessoaCadastro = new javax.swing.JMenuItem();
        mnuProdutoCadastro = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuRelatorio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        mnuArquivo.setText("Arquivo");

        mnuSairSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.fw.png"))); // NOI18N
        mnuSairSistema.setText("Sair");
        mnuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairSistemaActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuSairSistema);

        jMenuBar1.add(mnuArquivo);

        mnuCadastro.setText("Cadastro");

        mnuPessoaCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroPessoas.fw.png"))); // NOI18N
        mnuPessoaCadastro.setText("Pessoa");
        mnuPessoaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPessoaCadastroActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuPessoaCadastro);

        mnuProdutoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CadastroProduto.fw.png"))); // NOI18N
        mnuProdutoCadastro.setText("Produto");
        mnuProdutoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutoCadastroActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuProdutoCadastro);

        jMenuItem2.setText("Vendas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuCadastro.add(jMenuItem2);

        jMenuBar1.add(mnuCadastro);

        mnuRelatorio.setText("Relatório");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Relatorio.fw.png"))); // NOI18N
        jMenuItem1.setText("Vendas");
        mnuRelatorio.add(jMenuItem1);

        jMenuBar1.add(mnuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(btnRelatorio)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnRelatorio)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairSistemaActionPerformed
        System.exit(1);
    }//GEN-LAST:event_mnuSairSistemaActionPerformed

    private void mnuPessoaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPessoaCadastroActionPerformed
        frmPessoaListagem janela = new frmPessoaListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuPessoaCadastroActionPerformed

    private void mnuProdutoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutoCadastroActionPerformed
        frmProdutoListagem janela = new frmProdutoListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuProdutoCadastroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmVendas janela = new frmVendas();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        Connection conn = null;
        try {
            // Obtém o diretório da aplicação
            String arquivo = System.getProperty("user.dir");

            // Carrega conexão via JDBC
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/testeconexao", "root", "");
            Statement sql = conn.createStatement();

            // Carrega fonte de dados
            ResultSet rs = sql.executeQuery("SELECT\n"
                    + "     pessoa.`codPessoa` AS pessoa_codPessoa,\n"
                    + "     pessoa.`nome` AS pessoa_nome,\n"
                    + "     pessoa.`DataNascimento` AS pessoa_DataNascimento\n"
                    + "FROM\n"
                    + "     `pessoa` pessoa");
            JRDataSource ds = new JRResultSetDataSource(rs);

            // Preenche o relatório com os dados
            JasperPrint print = JasperFillManager.fillReport(arquivo + "/src/br/edu/ifnmg/tads/sistemavendas/Presentation/PrimeiroRelatorio.jasper", null, ds);

            // Exibe visualização dos dados
            JasperViewer.viewReport(print, false);

        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuPessoaCadastro;
    private javax.swing.JMenuItem mnuProdutoCadastro;
    private javax.swing.JMenu mnuRelatorio;
    private javax.swing.JMenuItem mnuSairSistema;
    // End of variables declaration//GEN-END:variables
}
