/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.sistemavendas.Presentation;

/**
 *
 * @author Diego
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuSairSistema = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        mnuPessoaCadastro = new javax.swing.JMenuItem();
        mnuProdutoCadastro = new javax.swing.JMenuItem();
        mnuRelatorio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuArquivo.setText("Arquivo");

        mnuSairSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.fw.png"))); // NOI18N
        mnuSairSistema.setText("Sair");
        mnuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairSistemaActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuSairSistema);

        jMenuBar1.add(mnuArquivo);

        mnuCadastro.setText("Cadastro");

        mnuPessoaCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroPessoas.fw.png"))); // NOI18N
        mnuPessoaCadastro.setText("Pessoa");
        mnuPessoaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPessoaCadastroActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuPessoaCadastro);

        mnuProdutoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CadastroProduto.fw.png"))); // NOI18N
        mnuProdutoCadastro.setText("Produto");
        mnuProdutoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutoCadastroActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuProdutoCadastro);

        jMenuBar1.add(mnuCadastro);

        mnuRelatorio.setText("Relatório");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Relatorio.fw.png"))); // NOI18N
        jMenuItem1.setText("Vendas");
        mnuRelatorio.add(jMenuItem1);

        jMenuBar1.add(mnuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairSistemaActionPerformed
        System.exit(1);
    }//GEN-LAST:event_mnuSairSistemaActionPerformed

    private void mnuPessoaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPessoaCadastroActionPerformed
        frmPessoaListagem janela = new frmPessoaListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuPessoaCadastroActionPerformed

    private void mnuProdutoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutoCadastroActionPerformed
        frmProdutoListagem janela = new frmProdutoListagem();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuProdutoCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuPessoaCadastro;
    private javax.swing.JMenuItem mnuProdutoCadastro;
    private javax.swing.JMenu mnuRelatorio;
    private javax.swing.JMenuItem mnuSairSistema;
    // End of variables declaration//GEN-END:variables
}
